In [55]:
import numpy as np
from scipy import linalg


Придумайте матрицы, которые обладают следующими свойствами:
* диагональная, ортогональная, но не единичная(!):
* верхнетреугольная, ортогональная:
* нижнетреугольная, ортогональная:
* матрица, у которой определитель = 1, и все элементы не равны 0

P.S. Во всех пунктах ответом должна быть ненулевая матрица размерности не менее 2!

Найдите собственные значения и собственные вектора матриц:
m = np.array([[2, 2],
[1, 3]])
print(m)

In [56]:
# диагональная, ортогональная, не единичная 
a = np.diag([0.5, 0.5, 4])
print(a)
det_a = np.linalg.det(a)
print(det_a)

[[0.5 0.  0. ]
 [0.  0.5 0. ]
 [0.  0.  4. ]]
1.0


In [57]:
# верхнетреугольная, ортогональная
b = np.triu([[0.5,3,-1],[1,2,0.5],[7,9,-1]], 0)
print(b)
det_b = np.linalg.det(b)
print(det_b)

[[ 0.5  3.  -1. ]
 [ 0.   2.   0.5]
 [ 0.   0.  -1. ]]
-1.0


In [58]:
# нижнетреугольная, ортогональная
c = np.tril([[0.5,3,-1],[1,2,0.5],[7,9,-1]], 0)
print(c)
det_c = np.linalg.det(c)
print(det_c)

[[ 0.5  0.   0. ]
 [ 1.   2.   0. ]
 [ 7.   9.  -1. ]]
-1.0


In [59]:
# матрица, у которой определитель = 1, и все элементы не равны 0
d = np.array([[1, 2], [-1, -1]])
print(c)
det_d = np.linalg.det(d)
print(det_d)

[[ 0.5  0.   0. ]
 [ 1.   2.   0. ]
 [ 7.   9.  -1. ]]
1.0


In [60]:
m = np.array([[2, 2], [1, 3]]) 
print(m)
w, v = np.linalg.eig(m)

[[2 2]
 [1 3]]


In [61]:
for i in range(len(w)):
    print("Собственное значение " + str(w[i]))
    print("соответствующий ему собственный вектор " + str(v[:,i]))

Собственное значение 1.0
соответствующий ему собственный вектор [-0.89442719  0.4472136 ]
Собственное значение 4.0
соответствующий ему собственный вектор [-0.70710678 -0.70710678]


In [62]:
# Найдите спектральное разложение матрицы:
m = np.array([[1, 2],
[2,3]])
print(m)

[[1 2]
 [2 3]]


In [63]:
e, U = linalg.eig(m)
print('Eigenvalues:')
print(np.array(e, dtype=float))
print('\nEigenvectors:')
print(U)

Eigenvalues:
[-0.23606798  4.23606798]

Eigenvectors:
[[-0.85065081 -0.52573111]
 [ 0.52573111 -0.85065081]]


/Users/Katerina/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:3: ComplexWarning: Casting complex values to real discards the imaginary part
  This is separate from the ipykernel package so we can avoid doing imports until
