#### Задание 1
Получить интуицию, на что влияют параметры распределений. Построить по 5 функций плотностей с разными параметрами для каждого распределения: нормальное, экспоненциальное, Стьюдента на одном графике.

In [9]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import scipy.stats as sts

%matplotlib inline

In [10]:
#нормальное
mu = 2.0
sigma = 0.6
norm_rv = sts.norm(loc=mu, scale=sigma)
norm_rv.rvs(10)

array([1.55773962, 1.91648903, 1.93874525, 2.47648885, 1.96757427,
       2.6499127 , 2.39594138, 1.47796378, 2.20048023, 1.97026508])

In [11]:
#экспоненциальное
lam = 0.1
expon_rv = sts.expon(lam)
expon_rv.rvs(10)

array([0.27181558, 0.56983884, 0.69243517, 1.74468602, 0.25629878,
       0.22081827, 1.01320034, 0.11276003, 1.42266631, 1.60709201])

In [17]:
#распределение Стьюдента
n = 10
t_rv = sts.t(n)
t_rv.rvs(10)

array([ 1.08786279e+00, -8.28245624e-01, -2.75093472e-01, -7.73528669e-01,
       -2.25709453e+00,  2.97839359e-01,  6.29395343e-01, -3.09188709e-01,
        8.38524125e-04, -8.52521993e-01])

In [20]:
x = np.linspace(-5,5,100)
pdf = norm_rv.pdf(x)
plt.plot(x, pdf)

pdf = expon_rv.pdf(x)
plt.plot(x, pdf)


pdf = t_rv.pdf(x)
plt.plot(x, pdf)


plt.ylabel('$f(x)$')
plt.xlabel('$x$')
plt.show()